<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title><?php $this->getPageTitle("-Mamute") ?></title>
  </head>
  <body>
        <?php require_once __DIR__."/layouts/menu.phtml"?>
        <?php $this->content() ?>

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="/assets/jquery-3.3.1.slim.min.js" ></script>
    <script src="/assets/popper/popper.min.js" ></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js" ></script>
  </body>
</html>



